// <auto-generated />
using System;
using HonorCouncil_RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HonorCouncil_RazorPages.Data.Migrations
{
    [DbContext(typeof(HonorCouncilDbContext))]
    [Migration("20260330174027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Appeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Grounds")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HonorCaseId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HonorCaseId")
                        .IsUnique();

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.AvailabilitySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FacultyMemberId")
                        .HasColumnType("int");

                    b.Property<int>("HonorCaseId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantRole")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedByEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("HonorCaseId");

                    b.HasIndex("StudentId");

                    b.ToTable("AvailabilitySlots");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.CaseStatusEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HonorCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("HonorCaseId");

                    b.ToTable("CaseStatusEntries");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Section")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Term")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.CourseFaculty", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyMemberId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "FacultyMemberId");

                    b.HasIndex("FacultyMemberId");

                    b.ToTable("CourseFacultyAssignments");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.EvidenceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("HonorCaseId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UploadedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UploadedByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HonorCaseId");

                    b.ToTable("EvidenceFiles");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.FacultyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("FacultyMembers");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Hearing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HearingFormat")
                        .HasColumnType("int");

                    b.Property<int>("HonorCaseId")
                        .HasColumnType("int");

                    b.Property<string>("LocationOrMeetingLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ScheduledStartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HonorCaseId")
                        .IsUnique();

                    b.ToTable("Hearings");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.HonorCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedInvestigatorId")
                        .HasColumnType("int");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("PriorityLabel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedInvestigatorId");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("HonorCases");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Investigator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Investigators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "aharper@jmu.edu",
                            FullName = "Alex Harper",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "mlee@jmu.edu",
                            FullName = "Morgan Lee",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HonorCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HonorCaseId");

                    b.HasIndex("ReportId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyMemberId")
                        .HasColumnType("int");

                    b.Property<bool>("IsWithinFormalFilingWindow")
                        .HasColumnType("bit");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ViolationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViolationDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("WasRedirectedToFormal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("FacultyMemberId");

                    b.HasIndex("ReportNumber")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Major")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Witness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HonorCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastNotifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("HonorCaseId");

                    b.ToTable("Witnesses");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Appeal", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.HonorCase", "HonorCase")
                        .WithOne("Appeal")
                        .HasForeignKey("HonorCouncil_RazorPages.Models.Appeal", "HonorCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HonorCase");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.AvailabilitySlot", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.FacultyMember", "FacultyMember")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HonorCouncil_RazorPages.Models.HonorCase", "HonorCase")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("HonorCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HonorCouncil_RazorPages.Models.Student", "Student")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FacultyMember");

                    b.Navigation("HonorCase");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.CaseStatusEntry", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.HonorCase", "HonorCase")
                        .WithMany("StatusTimeline")
                        .HasForeignKey("HonorCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HonorCase");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.CourseFaculty", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.Course", "Course")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HonorCouncil_RazorPages.Models.FacultyMember", "FacultyMember")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("FacultyMember");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.EvidenceFile", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.HonorCase", "HonorCase")
                        .WithMany("EvidenceFiles")
                        .HasForeignKey("HonorCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HonorCase");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Hearing", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.HonorCase", "HonorCase")
                        .WithOne("Hearing")
                        .HasForeignKey("HonorCouncil_RazorPages.Models.Hearing", "HonorCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HonorCase");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.HonorCase", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.Investigator", "AssignedInvestigator")
                        .WithMany("AssignedCases")
                        .HasForeignKey("AssignedInvestigatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HonorCouncil_RazorPages.Models.Report", "Report")
                        .WithOne("HonorCase")
                        .HasForeignKey("HonorCouncil_RazorPages.Models.HonorCase", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedInvestigator");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.NotificationLog", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.HonorCase", "HonorCase")
                        .WithMany("Notifications")
                        .HasForeignKey("HonorCaseId");

                    b.HasOne("HonorCouncil_RazorPages.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId");

                    b.Navigation("HonorCase");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Report", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.Course", "Course")
                        .WithMany("Reports")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HonorCouncil_RazorPages.Models.FacultyMember", "FacultyMember")
                        .WithMany("Reports")
                        .HasForeignKey("FacultyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HonorCouncil_RazorPages.Models.Student", "Student")
                        .WithMany("Reports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("FacultyMember");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Witness", b =>
                {
                    b.HasOne("HonorCouncil_RazorPages.Models.HonorCase", "HonorCase")
                        .WithMany("Witnesses")
                        .HasForeignKey("HonorCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HonorCase");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Course", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.FacultyMember", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("CourseAssignments");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.HonorCase", b =>
                {
                    b.Navigation("Appeal");

                    b.Navigation("AvailabilitySlots");

                    b.Navigation("EvidenceFiles");

                    b.Navigation("Hearing");

                    b.Navigation("Notifications");

                    b.Navigation("StatusTimeline");

                    b.Navigation("Witnesses");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Investigator", b =>
                {
                    b.Navigation("AssignedCases");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Report", b =>
                {
                    b.Navigation("HonorCase");
                });

            modelBuilder.Entity("HonorCouncil_RazorPages.Models.Student", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
